### ISSUE TITLE
Add command option to print statistics

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.aare#3]
I'd be interested in the max and min (called "extrema") temperature of the last 7 days.

Example usage: `aare --statistics`

Example output:

```
2018-02-18: min 3.4° C, max 5.6° C
2018-02-19: min 6.2° C, max 7.4° C
2018-02-20: min 7.9° C, max 8.6° C
etc.
```

Get the data from the archive, e.g. http://aare.schwumm.ch/api/archive?from=2018-02-16&data=temperature

**Comment by stevenpi** [comment]
resolved by commit 6c326df30da13b29c8caf830f8ea8b62b9fc5ab9
