### ISSUE TITLE
Change Packageowner in Manifest

### ISSUE THREAD

**Issue by stevenpi** [4teamwork/ftw.aare#6]
The package owner is currently set to `stevenpi` which is incorrect. 
Change it to `4teamwork`

**Comment by mbaechtold** [comment]
This can be changed in the `setup.py`.

You could pass `maintainer='Steven Pilatschek'` to `setup()`.

Example:

```python
setup(
    ...
    author='4teamwork AG',
    author_email='info@4teamwork.ch',
    maintainer='Steven Pilatschek',
    ...
)
```
